# Tarefa 03

- Leia os enunciados com atenção
- Saiba que pode haver mais de uma resposta correta
- Insira novas células de código sempre que achar necessário
- Em caso de dúvidas, procure os Tutores
- Divirta-se :)

In [8]:
import pandas as pd
import requests

####  1) Lendo de APIs
Vimos em aula como carregar dados públicos do governo através de um API (*Application Programming Interface*). No exemplo de aula, baixamos os dados de pedidos de verificação de limites (PVL) realizados por estados, e selecionamos apenas aqueles referentes ao estado de São Paulo.

1. Repita os mesmos passos feitos em aula, mas selecione os PVLs realizados por municípios no estado do Rio de Janeiro.
2. Quais são os três *status* das solicitações mais frequentes na base? Quais são suas frequências?
3. Construa uma nova variável que contenha o ano do **status**. Observe que ```data_status``` vem como tipo *object* no **DataFrame**. Dica: você pode usar o método ```.str``` para transformar o tipo da variável em string, em seguida um método como [**slice()**](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.slice.html) ou [**split()**](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.split.html).
4. Indique a frequência de cada ano do campo construído no item (3).

In [9]:
### Para fazer essa parte tive que transformar os json em csv e subir em um repositorio no GitHub o requests parou de funcionar.

In [10]:
# 1) Seu código aqui
municipio_rio = pd.read_csv('https://raw.githubusercontent.com/harleiaki/aqui_arquivos/main/rj_municipio.csv.csv')
municipio_rio.head()

,items__id_pleito,items__tipo_interessado,items__interessado,items__cod_ibge,items__uf,items__num_pvl,items__status,items__num_processo,items__data_protocolo,items__tipo_operacao,...,items__valor,items__pvl_assoc_divida,items__pvl_contradado_credor,items__data_status,hasMore,limit,offset,count,links__rel,links__href
0,9970,Município,Queimados,3304144,RJ,NaN,Deferido,17944.001090/2012-41,2012-07-16T03:00:00Z,Operação contratual interna,...,3349620.0,0,0,13/08/2012,False,5000.0,0.0,235.0,self,http://apidatalake-ords.apps.ocp.tesouro.gov.b...
1,10412,Município,Maricá,3302700,RJ,NaN,Arquivado por decurso de prazo,17944.001193/2011-20,2012-09-12T03:00:00Z,Operação contratual interna,...,22800000.0,0,0,17/10/2012,NaN,NaN,NaN,NaN,describedby,http://apidatalake-ords.apps.ocp.tesouro.gov.b...
2,9234,Município,Nova Friburgo,3303401,RJ,NaN,Deferido,17944.000933/2013-72,2013-08-30T03:00:00Z,Operação contratual interna,...,14000000.0,1,0,09/10/2013,NaN,NaN,NaN,NaN,first,http://apidatalake-ords.apps.ocp.tesouro.gov.b...
3,11690,Município,Tanguá,3305752,RJ,NaN,Arquivado,17944.001503/2008-19,2008-11-04T02:00:00Z,Operação contratual interna,...,300381.0,0,0,06/02/2009,NaN,NaN,NaN,NaN,NaN,NaN
4,13753,Município,Piraí,3304003,RJ,NaN,Deferido,19405.000071/2002-58,2002-09-30T03:00:00Z,Operação contratual interna,...,408600.0,0,0,11/10/2002,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
# 2) Seu código aqui
municipio_rio.items__status.value_counts()

Deferido                                                 94
Arquivado                                                53
Regularizado                                             25
Arquivado por decurso de prazo                           23
Deferido (PVL-IF)                                        16
Encaminhado à PGFN com manifestação técnica favorável    13
Arquivado a pedido                                        6
Em retificação pelo interessado                           2
Em análise                                                1
Pendente de regularização                                 1
Em retificação pelo interessado (PVL-IF)                  1
Name: items__status, dtype: int64

In [12]:
municipio_rio.items__valor.value_counts()

2.000000e+07    4
1.000000e+08    4
4.007000e+05    3
1.500000e+07    3
3.000000e+07    3
               ..
1.300029e+06    1
1.836200e+07    1
8.187062e+06    1
2.923200e+08    1
2.167932e+06    1
Name: items__valor, Length: 203, dtype: int64

In [13]:
municipio_rio.items__interessado.value_counts()

Rio de Janeiro                   41
Resende                          15
Nova Iguaçu                      14
Duque de Caxias                  11
Niterói                           9
                                 ..
Silva Jardim                      1
Duas Barras                       1
Cachoeiras de Macacu              1
Araruama                          1
São José do Vale do Rio Preto     1
Name: items__interessado, Length: 61, dtype: int64

In [14]:
# 3) Seu código aqui
municipio_rio.dtypes

items__id_pleito                  int64
items__tipo_interessado          object
items__interessado               object
items__cod_ibge                   int64
items__uf                        object
items__num_pvl                   object
items__status                    object
items__num_processo              object
items__data_protocolo            object
items__tipo_operacao             object
items__finalidade                object
items__tipo_credor               object
items__credor                    object
items__moeda                     object
items__valor                    float64
items__pvl_assoc_divida           int64
items__pvl_contradado_credor      int64
items__data_status               object
hasMore                          object
limit                           float64
offset                          float64
count                           float64
links__rel                       object
links__href                      object
dtype: object

In [15]:
pd.DataFrame(municipio_rio['items__data_status'])

    items__data_status
0           13/08/2012
1           17/10/2012
2           09/10/2013
3           06/02/2009
4           11/10/2002
..                 ...
230         08/05/2008
231         24/03/2014
232         24/11/2010
233         11/06/2014
234         29/06/2012

[235 rows x 1 columns]

In [16]:
municipio_rio.items__data_status.explode()

0      13/08/2012
1      17/10/2012
2      09/10/2013
3      06/02/2009
4      11/10/2002
          ...
230    08/05/2008
231    24/03/2014
232    24/11/2010
233    11/06/2014
234    29/06/2012
Name: items__data_status, Length: 235, dtype: object

In [17]:
municipio_rio['items__interessado'].value_counts()

Rio de Janeiro                   41
Resende                          15
Nova Iguaçu                      14
Duque de Caxias                  11
Niterói                           9
                                 ..
Silva Jardim                      1
Duas Barras                       1
Cachoeiras de Macacu              1
Araruama                          1
São José do Vale do Rio Preto     1
Name: items__interessado, Length: 61, dtype: int64

In [18]:
df = pd.DataFrame(municipio_rio,columns=['items__interessado','items__data_status'])
print (df)

                items__interessado items__data_status
0                        Queimados         13/08/2012
1                           Maricá         17/10/2012
2                    Nova Friburgo         09/10/2013
3                           Tanguá         06/02/2009
4                            Piraí         11/10/2002
..                             ...                ...
230  São José do Vale do Rio Preto         08/05/2008
231                  Volta Redonda         24/03/2014
232                 Rio de Janeiro         24/11/2010
233                        Resende         11/06/2014
234                         Quatis         29/06/2012

[235 rows x 2 columns]

In [19]:
df.items__interessado.value_counts()
df.items__data_status.value_counts()

25/05/2007    6
02/08/2007    5
30/10/2008    5
29/06/2012    4
26/06/2007    4
             ..
06/08/2014    1
17/07/2007    1
10/09/2007    1
12/01/2007    1
24/11/2010    1
Name: items__data_status, Length: 178, dtype: int64

####  2) Melhorando a interação com o API
Observe dois URLs de consultas diferentes, por exemplo o URL utilizado em aula, e o URL feito no exercício anterior. Compare-os e observe as diferenças.

1. Faça uma função em Python que recebe como argumento o UF da consulta e o tipo de interessado (```'Estado'```ou ```Município```), e que devolve os dados da consulta no formato *DataFrame*.
2. Quantas solicitações para o Estado podem ser consultadas para Minas Gerais com *status* em 'Arquivado por decurso de prazo' estão registradas?
3. Qual é o município da Bahia com mais solicitações deferidas?
4. Salve um arquivo .csv com os dados de solicitações da Bahia, com interessado = 'Estado'

In [20]:
#Aqui municipio BA 'https://raw.githubusercontent.com/harleiaki/aqui_arquivos/main/BA.csv.csv'
#Aqui estado MG 'https://raw.githubusercontent.com/harleiaki/aqui_arquivos/main/MG.csv.csv'

In [21]:
#1) Seu código aqui
estado_mg = pd.read_csv ('https://raw.githubusercontent.com/harleiaki/aqui_arquivos/main/MG.csv.csv')
estado_mg.head()
#Aqui DataFrame de estado de MG

,items__id_pleito,items__tipo_interessado,items__interessado,items__cod_ibge,items__uf,items__num_pvl,items__status,items__num_processo,items__data_protocolo,items__tipo_operacao,...,items__valor,items__pvl_assoc_divida,items__pvl_contradado_credor,items__data_status,hasMore,limit,offset,count,links__rel,links__href
0,9197,Estado,Minas Gerais,31,MG,NaN,Encaminhado à PGFN com manifestação técnica fa...,17944.000924/2009-03,2010-03-10T03:00:00Z,Operação contratual externa (com garantia da U...,...,5.000000e+07,1,0,01/04/2010,False,5000.0,0.0,40.0,self,http://apidatalake-ords.apps.ocp.tesouro.gov.b...
1,7280,Estado,Minas Gerais,31,MG,NaN,Deferido,17944.000537/2010-01,2010-06-24T03:00:00Z,Operação contratual interna,...,3.488900e+07,1,0,25/06/2010,NaN,NaN,NaN,NaN,describedby,http://apidatalake-ords.apps.ocp.tesouro.gov.b...
2,4926,Estado,Minas Gerais,31,MG,NaN,Arquivado,10951.000367/1998-24,1998-05-12T03:00:00Z,Operação contratual externa (com garantia da U...,...,1.650000e+08,0,0,24/07/2002,NaN,NaN,NaN,NaN,first,http://apidatalake-ords.apps.ocp.tesouro.gov.b...
3,13447,Estado,Minas Gerais,31,MG,NaN,Encaminhado à PGFN com manifestação técnica fa...,19405.000002/2006-78,2009-02-02T02:00:00Z,Operação contratual externa (com garantia da U...,...,1.000000e+07,1,0,12/11/2009,NaN,NaN,NaN,NaN,NaN,NaN
4,5828,Estado,Minas Gerais,31,MG,NaN,Encaminhado à PGFN com manifestação técnica fa...,17944.000208/2013-02,2013-07-16T03:00:00Z,Operação contratual interna (com garantia da U...,...,1.500000e+09,1,0,12/08/2013,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
df = pd.DataFrame(estado_mg,columns=['items__id_pleito'])
print (df)

    items__id_pleito
0               9197
1               7280
2               4926
3              13447
4               5828
5              10338
6              11054
7               7435
8               6811
9              11132
10             13602
11             13275
12             11571
13              7023
14             10011
15             13641
16             11696
17              7032
18             13618
19             11328
20             13587
21             20458
22             13672
23             13695
24             13549
25             13595
26              6917
27              5582
28             10265
29             27063
30              5967
31              7002
32             12286
33             13441
34             20534
35             22379
36             10294
37              7419
38              8255
39             22380

In [23]:
# 2) Seu código aqui
estado_mg.dtypes
#Nao entendi 'Arquivado por decurso de prazo'

items__id_pleito                  int64
items__tipo_interessado          object
items__interessado               object
items__cod_ibge                   int64
items__uf                        object
items__num_pvl                   object
items__status                    object
items__num_processo              object
items__data_protocolo            object
items__tipo_operacao             object
items__finalidade                object
items__tipo_credor               object
items__credor                    object
items__moeda                     object
items__valor                    float64
items__pvl_assoc_divida           int64
items__pvl_contradado_credor      int64
items__data_status               object
hasMore                          object
limit                           float64
offset                          float64
count                           float64
links__rel                       object
links__href                      object
dtype: object

In [24]:
# 3) Seu código aqui
municipio_ba = pd.read_csv ('https://raw.githubusercontent.com/harleiaki/aqui_arquivos/main/BA.csv.csv')
municipio_ba.head()

,items__id_pleito,items__tipo_interessado,items__interessado,items__cod_ibge,items__uf,items__num_pvl,items__status,items__num_processo,items__data_protocolo,items__tipo_operacao,...,items__valor,items__pvl_assoc_divida,items__pvl_contradado_credor,items__data_status,hasMore,limit,offset,count,links__rel,links__href
0,10410,Município,Conde,2908606,BA,NaN,Deferido,17944.001193/2008-24,2008-08-08T03:00:00Z,Operação contratual interna,...,500000.00,0,0,18/08/2008,False,5000.0,0.0,894.0,self,http://apidatalake-ords.apps.ocp.tesouro.gov.b...
1,10421,Município,Feira de Santana,2910800,BA,NaN,Regularizado,17944.001195/2013-81,2013-09-25T03:00:00Z,Operação contratual interna,...,4814974.97,0,0,14/11/2013,NaN,NaN,NaN,NaN,describedby,http://apidatalake-ords.apps.ocp.tesouro.gov.b...
2,10446,Município,Quijingue,2925907,BA,NaN,Arquivado por decurso de prazo,17944.001202/2009-68,2009-12-14T02:00:00Z,Operação contratual interna,...,130000.00,0,0,24/01/2011,NaN,NaN,NaN,NaN,first,http://apidatalake-ords.apps.ocp.tesouro.gov.b...
3,11971,Município,Presidente Tancredo Neves,2925758,BA,NaN,Em retificação pelo interessado,17944.001571/2007-99,2022-12-21T03:00:00Z,Operação contratual interna,...,26679.24,1,0,23/12/2022,NaN,NaN,NaN,NaN,NaN,NaN
4,10747,Município,Lauro de Freitas,2919207,BA,NaN,Deferido,17944.001273/2011-85,2012-01-20T02:00:00Z,Operação contratual interna,...,1138293.09,1,0,08/02/2012,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
municipio_ba.items__interessado.value_counts()

Camaçari                  19
Salvador                  17
Luís Eduardo Magalhães    15
Vitória da Conquista      14
Amargosa                  14
                          ..
Ituaçu                     1
Ribeira do Pombal          1
Lafaiete Coutinho          1
Quixabeira                 1
Lençóis                    1
Name: items__interessado, Length: 289, dtype: int64

In [30]:
# 4) Seu código aqui
df = pd.DataFrame(municipio_ba,columns=['items__interessado'])
print (df)

            items__interessado
0                        Conde
1             Feira de Santana
2                    Quijingue
3    Presidente Tancredo Neves
4             Lauro de Freitas
..                         ...
889                    Brejões
890                      Irecê
891                   Alcobaça
892                     Pindaí
893                    Central

[894 rows x 1 columns]

In [31]:
df.rename(columns={'items__interessado':'Estado'})

                        Estado
0                        Conde
1             Feira de Santana
2                    Quijingue
3    Presidente Tancredo Neves
4             Lauro de Freitas
..                         ...
889                    Brejões
890                      Irecê
891                   Alcobaça
892                     Pindaí
893                    Central

[894 rows x 1 columns]

In [27]:
df.to_csv('salvando_projeto-6.csv')